name: xml_annotation
description: Classes and helper functions that support XML code generation via the `xml_serializable` package.
version: 2.0.0-nullsafety.0
homepage: https://github.com/tnc1997/dart-xml-serializable

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  xml: ^5.0.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
