name: xml_serializable
description: Automatically generate code for converting to and from XML by annotating Dart classes.
version: 2.5.3
homepage: https://github.com/tnc1997/dart-xml-serializable

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  analyzer: '>=5.2.0 <7.0.0'
  build: ^2.0.0
  build_config: ^1.0.0
  recase: ^4.0.0
  source_gen: ^1.0.0
  source_helper: ^1.0.0
  xml: '>=5.0.0 <7.0.0'
  xml_annotation: ^2.4.0

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  lints: ^5.0.0
  source_gen_test: ^1.0.0
  test: ^1.16.6

dependency_overrides:
  source_gen_test:
    git:
      ref: feat/29
      url: https://github.com/tnc1997/dart-source-gen-test.git
