name: xml_serializable
description: Automatically generate code for converting to and from XML by annotating Dart classes.
version: 2.2.0
homepage: https://github.com/tnc1997/dart-xml-serializable

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: '>=2.0.0 <5.0.0'
  build: ^2.0.0
  build_config: ^1.0.0
  source_gen: ^1.0.0
  xml: '>=5.0.0 <7.0.0'
  xml_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.0.0
  lints: ^1.0.0
  test: ^1.16.0

dependency_overrides:
  xml_annotation:
    path: ../xml_annotation
